version: '2.1'
services:
  apollo_server_go:
    container_name: apollo_server_go
    hostname: apollo_server_go
    build: .
    volumes:
      - "./config.json:/config.json"
      - "./configs:/configs"
    working_dir: /app
    environment:
      - GIN_MODE=release
      - CONFIG_FORMAT=properties
      - URL_PREFIX=http://apollo.local
      - PORT=80
    ports:
      - "8070:80"
    network_mode: bridge
